name: lectures

channels:
    - conda-forge
    - bioconda
    - defaults
    - r

dependencies:
    # Jupyter
    - python=3.8
    - jupyter=1.0
    - pandas=1.0
    - rise=5.6
    - seaborn=0.10
    - rpy2=3.1
    - r::r-base=3.6
