site_name: NBIS Tools for Reproducible Research
theme:
    name: readthedocs
    custom_dir: docs_custom/
pages:
  - Welcome: 'index.md'
  - About: 'about.md'
  - Practicalities:
    - Schedule: 'schedule.md'
    - 'Travel info': 'travel.md'
    - Lectures: 'lectures.md'
    - Feedback: 'feedback.md'
    - Setup: 'setup.md'
  - Tutorials:
    - Introduction: 'introduction.md'
    - Git: 'git.md'
    - Conda: 'conda.md'
    - Snakemake: 'snakemake.md'
    - R Markdown: 'rmarkdown.md'
    - Jupyter: 'jupyter.md'
    - Docker: 'docker.md'
    - Singularity: 'singularity.md'
    - 'Making a project reproducible': 'project.md'
    - 'Take down': 'take_down.md'

markdown_extensions:
  - toc:
      permalink: 
  - admonition
  - pymdownx.arithmatex
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.superfences
extra_css: [extra.css]
