site_name: NBIS Tools for Reproducible Research
docs_dir: 'lectures'
theme:
    name: readthedocs
nav:
  - Lectures: 'index.md'

markdown_extensions:
  - toc:
      permalink: 
  - admonition
  - pymdownx.arithmatex
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.superfences
extra_css:
  - template.css
