site_name: NBIS Reproducible research course
docs_dir: 'lectures'
theme:
    name: readthedocs
    custom_dir: docs_custom/
pages:
  - Lectures: 'README.md'

markdown_extensions:
  - toc:
      permalink: 
  - admonition
  - pymdownx.arithmatex
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.superfences
extra_css:
  - template.css
