name: rmarkdown-env
channels:
  - conda-forge
  - bioconda
  - main
  - r
dependencies:
  - r-base=3.6.1
  - rstudio=1.1.456
  - r-devtools=2.3.2
  - r-ggplot2=3.3.2
  - r-networkd3=0.4
  - r-pheatmap=1.0.12
  - r-reshape2=1.4.4
  - r-rmarkdown=2.5
  - r-stringi=1.4.6
  - bioconductor-rtracklayer=1.46.0
  - bioconductor-geoquery=2.54.0
