channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - fastqc=0.11.9
  - sra-tools=2.10.1
  - python=3.7.6
  - snakemake-minimal=5.10.0
  - graphviz=2.42.3
  - xorg-libxrender
  - xorg-libxpm
  - wget=1.20.1
