name: docker

on:
  workflow_dispatch:
    branches:
      - main
      - devel
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker-build-and-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker build
        run: |
          docker build -t my_docker_project -f docker/Dockerfile docker/
          docker run --rm my_docker_project